package com.atlassian.theplugin.commons.crucible.api.model;

public enum ReviewDiffType {
	REVIEW_CHANGED,
	NEW_REVIEW_ITEM,
	NEW_GENERAL_COMMENT,
	NEW_VERSIONED_COMMENT,
	NEW_REPLY,
	UPDATED_GENERAL_COMMENT,
	UPDATED_VERSIONED_COMMENT,
	UPDATED_REPLY,
	DELETED_GENERAL_COMMENT,
	DELETED_VERSIONED_COMMENT,
	DELETED_REPLY,
	REVIEWER_COMPLETED,
	REVIEW_COMPLETED,
	REVIEW_STATE_CHANGED
}

